package com.founderos.backend.service;
import com.founderos.backend.api.ApiModels.*; import com.founderos.backend.client.OrchestratorClient; import com.founderos.backend.domain.*; import com.founderos.backend.repository.*; import org.springframework.stereotype.Service; import java.util.*;
@Service
public class FounderOsService {
 private final ProjectRepository projects; private final DecisionRepository decisions; private final ArtifactRepository artifacts; private final WorkflowRunRepository workflows; private final OrchestratorClient orchestrator;
 public FounderOsService(ProjectRepository projects,DecisionRepository decisions,ArtifactRepository artifacts,WorkflowRunRepository workflows,OrchestratorClient orchestrator){this.projects=projects;this.decisions=decisions;this.artifacts=artifacts;this.workflows=workflows;this.orchestrator=orchestrator;}
 public CreateProjectResponse create(CreateProjectRequest request){Project p=projects.save(new Project(request.name().trim(),request.idea().trim()));String threadId="project-"+p.getId();WorkflowRun run=workflows.save(new WorkflowRun(p.getId(),threadId));try{var result=orchestrator.start(p.getId(),threadId,p.getName(),p.getIdea());if(result==null||result.decision()==null||!threadId.equals(result.threadId()))throw new IllegalStateException("Orchestrator returned an invalid start response");FounderDecision d=decisions.save(new FounderDecision(p.getId(),threadId,result.decision().question(),result.decision().options(),result.decision().recommendation(),result.decision().context()));p.waiting(threadId);run.waiting(result.currentNode());projects.save(p);workflows.save(run);return new CreateProjectResponse(ProjectView.of(p),DecisionView.of(d));}catch(RuntimeException e){p.failed();run.failed(e.getMessage());projects.save(p);workflows.save(run);throw e;}}
 public ProjectDetail getProject(UUID id){Project p=projects.findById(id).orElseThrow(()->new NotFoundException("Project not found"));var ds=decisions.findByProjectIdOrderByCreatedAtAsc(id).stream().map(DecisionView::of).toList();var as=artifacts.findByProjectIdOrderByVersionAsc(id).stream().map(ArtifactView::of).toList();var w=workflows.findByProjectId(id).map(WorkflowView::of).orElse(null);return new ProjectDetail(ProjectView.of(p),ds,w,as);}
 public ArtifactView getArtifact(UUID id){return artifacts.findById(id).map(ArtifactView::of).orElseThrow(()->new NotFoundException("Artifact not found"));}
 public ResolveDecisionResponse resolve(UUID id,ResolveDecisionRequest request){FounderDecision d=decisions.findById(id).orElseThrow(()->new NotFoundException("Decision not found"));if(d.getStatus()!=DecisionStatus.OPEN)throw new ConflictException("Decision is already resolved");if(!d.getOptions().contains(request.selectedOption()))throw new IllegalArgumentException("Selected option is not one of the available options");Project p=projects.findById(d.getProjectId()).orElseThrow(()->new NotFoundException("Project not found"));WorkflowRun run=workflows.findByProjectId(p.getId()).orElseThrow(()->new NotFoundException("Workflow run not found"));if(p.getWorkflowThreadId()==null||!p.getWorkflowThreadId().equals(d.getWorkflowThreadId()))throw new ConflictException("Missing or mismatched workflow thread");d.resolve(request.selectedOption(),request.comment());p.defining();decisions.save(d);projects.save(p);try{var result=orchestrator.resume(run.getThreadId(),request.selectedOption(),request.comment());if(result==null||result.artifact()==null||!run.getThreadId().equals(result.threadId()))throw new IllegalStateException("Orchestrator returned an invalid resume response");Artifact a=artifacts.findByProjectIdAndTypeAndVersion(p.getId(),"PRODUCT_BRIEF",1).orElseGet(()->artifacts.save(new Artifact(p.getId(),result.artifact().type(),result.artifact().title(),result.artifact().content(),1)));run.completed();p.completed();workflows.save(run);projects.save(p);return new ResolveDecisionResponse(p.getId(),p.getStatus(),ArtifactView.of(a));}catch(RuntimeException e){p.failed();run.failed(e.getMessage());projects.save(p);workflows.save(run);throw e;}}
}
