package com.founderos.backend.integration;
import com.founderos.backend.client.OrchestratorClient; import com.founderos.backend.client.OrchestratorClient.*; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.test.context.bean.override.mockito.MockitoBean; import org.springframework.test.web.servlet.MockMvc; import org.testcontainers.containers.PostgreSQLContainer; import org.testcontainers.junit.jupiter.Container; import org.testcontainers.junit.jupiter.Testcontainers; import org.springframework.test.context.DynamicPropertyRegistry; import org.springframework.test.context.DynamicPropertySource; import java.util.List; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest @AutoConfigureMockMvc @Testcontainers
class FounderOsApiIntegrationTest {
 @Container static PostgreSQLContainer<?> postgres=new PostgreSQLContainer<>("postgres:16-alpine");
 @DynamicPropertySource static void properties(DynamicPropertyRegistry r){r.add("spring.datasource.url",postgres::getJdbcUrl);r.add("spring.datasource.username",postgres::getUsername);r.add("spring.datasource.password",postgres::getPassword);}
 @Autowired MockMvc mvc; @MockitoBean OrchestratorClient orchestrator;
 @BeforeEach void stub(){when(orchestrator.start(any(),anyString(),anyString(),anyString())).thenAnswer(i->new StartResponse(i.getArgument(1),"WAITING_FOR_FOUNDER","wait_for_founder",new DecisionPayload("Who should the first version serve?",List.of("Beginner investors","Experienced non-programmers","Professional quant traders"),"Experienced non-programmers","context")));when(orchestrator.resume(anyString(),anyString(),nullable(String.class))).thenAnswer(i->new ResumeResponse(i.getArgument(0),"COMPLETED","end",new ArtifactPayload("PRODUCT_BRIEF","Tradigo Product Brief","# Tradigo Product Brief\nExperienced non-programmers")));}
 @Test void completeWorkflowAndEnforceDecisionRules() throws Exception {String created=mvc.perform(post("/api/projects").contentType("application/json").content("{\"name\":\"Tradigo\",\"idea\":\"No-code strategies\"}")).andExpect(status().isCreated()).andExpect(jsonPath("$.project.status").value("WAITING_FOR_FOUNDER")).andExpect(jsonPath("$.decision.status").value("OPEN")).andReturn().getResponse().getContentAsString();var json=new com.fasterxml.jackson.databind.ObjectMapper().readTree(created);String projectId=json.at("/project/id").asText();String decisionId=json.at("/decision/id").asText();mvc.perform(post("/api/decisions/"+decisionId+"/resolve").contentType("application/json").content("{\"selectedOption\":\"not valid\"}")).andExpect(status().isBadRequest());mvc.perform(post("/api/decisions/"+decisionId+"/resolve").contentType("application/json").content("{\"selectedOption\":\"Experienced non-programmers\",\"comment\":\"Australia first\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("COMPLETED")).andExpect(jsonPath("$.artifact.type").value("PRODUCT_BRIEF"));mvc.perform(get("/api/projects/"+projectId)).andExpect(status().isOk()).andExpect(jsonPath("$.project.status").value("COMPLETED")).andExpect(jsonPath("$.workflow.status").value("COMPLETED")).andExpect(jsonPath("$.artifacts.length()").value(1));mvc.perform(post("/api/decisions/"+decisionId+"/resolve").contentType("application/json").content("{\"selectedOption\":\"Experienced non-programmers\"}")).andExpect(status().isConflict());}
 @Test void validatesProjectInput() throws Exception {mvc.perform(post("/api/projects").contentType("application/json").content("{\"name\":\"\",\"idea\":\"\"}")).andExpect(status().isBadRequest());}
}
